name: Publish to Github pages

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@2.1.1

    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: npm install

    - name: build static website
      run: npx gatsby build
    
    - name: publish
      run: npx gh-pages -d public -b master -r $${ secrets.repo_with_token }
